CREATE TABLE habit
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       VARCHAR(255),
    description VARCHAR(255),
    frequency   INTEGER                                 NOT NULL,
    mood        DOUBLE PRECISION                        NOT NULL,
    CONSTRAINT pk_habit PRIMARY KEY (id)
);